I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 188, in script
    show yami side eye with fadeout
  File "game/script.rpy", line 188, in <module>
    show yami side eye with fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 188, in script
    show yami side eye with fadeout
  File "C:\Users\elhlyn11_ecolecathol\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\elhlyn11_ecolecathol\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\elhlyn11_ecolecathol\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 188, in <module>
    show yami side eye with fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
Lovelorn Reality 1.0
Fri Jan 10 09:38:20 2025
